### ISSUE TITLE
Select Pre-view Version

### ISSUE THREAD

**Issue by rikgale** [mypiaware/virtual-radar-server-installation#15]
Would it be possible to add functionality to the script to select which pre-view version is installed. e.g. V3.0preview8, V3.0preview9, V3.0preview10?
There is bug in the latest V3.0 preview 10 which is affecting the localaircraft.txt processing and I would like to be able to rollback to V3.0 preview 9.
Thank you

**Comment by mypiaware** [comment]
Greetings,

Unfortunately, it is not possible at all.  As far as I can tell, with any new release of a preview version, all of the files for the previous version are simply deleted and replaced with the files of the newest version.  Unless the older files have been moved/archived to some location I do not know about, it is not possible to access any other preview version except for the latest version.

You can test this yourself by taking a URL of one of the latest files and simply replacing the version number in the URL with an older number.  The download will fail because the URL does not exist.

I would suggest routinely checking the [VRS Preview](http://www.virtualradarserver.co.uk/Preview.aspx) webpage and download all the files from the GitHub site for every preview version that is released.  If you ever want to revert to an older version, you can always just do the downgrade yourself by unpacking the *.tar.gz files of an older version.  Of course, this does not help your current predicament, but it is still an idea to thing about for the future.

**Comment by rikgale** [comment]
Thanks for getting back to me on this. I have had a good hunt about and I am unable to find older versions. You have given me one idea which is to copy the entire VRS from one linux box  to the other. 
I don't suppose you know off-hand all the folders VRS puts files into?

**Comment by mypiaware** [comment]
Yeah, you can simply copy/paste files from another VRS server.  You should be able to do it without any issue.

If you are using my script, the default location for all the program files will be within this directory:
`~/VirtualRadarServer/Installation/`

Any plugin will be in `~/VirtualRadarServer/Installation/Plugins/` in its own sub-directory.

More specifically, you can try the following.  I am making an assumption you have used my script for your VRS installation.

On the server with the older VRS files, copy all VRS files with this command:
`tar -cf "$HOME/vrs_program.tar" "$HOME/VirtualRadarServer"`

The `vrs_program.tar` file will be in your home directory.  Copy the `vrs_program.tar` file to the home directory on the server you desire to have the older VRS files.

On the server you want to have the older VRS files, use this command to restore the files:
`tar -xf "$HOME/vrs_program.tar" -C /`

On the second server, you will have all of your VRS files (program & plugins) and personal files such as pictures and silhouettes.

Hope this helps.

**Comment by rikgale** [comment]
Perfect! Yes - I only ever use your script to install VRS.

I will try your tar method when I am at home later and feedback

Thank you.

**Comment by mypiaware** [comment]
Oh, and for the sake of completeness, you should also copy the user files from the old VRS server:
`tar -cf "$HOME/vrs_local.tar" "$HOME/.local/share/VirtualRadar"`

Then, on the second server, perform an extractions as well:
`tar -xf "$HOME/vrs_local.tar" -C /`

Those two *.tar files alone will backup 100% of your VRS.  (By the way, I have a cronjob that essentially does this every night.  My two *.tar files get saved to an external USB drive.  If my server completely dies, I can restore my VRS extremely fast.)

**Comment by rikgale** [comment]
After thinking that this had failed to work it turned out that having different user name between the installations I thought it had not worked, but it worked perfectly, but I had not noticed it ended up in `/home/pi` rather than `/home/richard`

Did a manual replace it all worked well.

Thank you for all the advice.

**Comment by mypiaware** [comment]
I did not think of the possibility of a different user name.  You will come across an issue with some settings that are configured to use the username of the original server.  This is due to two configuration files in the local user (`~/.local/share`) directory that have the username embedded in it.  I also thought of a different way to use the tar command that will avoid having the username within it.

Complete steps to transfer VRS from one server to a second server with a different username:

**On the original server:**

- `tar -cf "$HOME/vrs_local.tar" -C "$HOME/.local/share" "VirtualRadar"`
- `tar -cf "$HOME/vrs_main.tar"  -C "$HOME" "VirtualRadarServer"`

**Copy the two tar files from the original server to the second server:**
- Place the two tar files in the home directory of the second server.

**On the second server:**

- Do a complete installation as normal with my script. (This is primarily just to create the `vrs` command.)
- `rm -rf "$HOME/.local/share/VirtualRadar"`
- `rm -rf "$HOME/VirtualRadarServer"`
- `tar -xf "$HOME/vrs_local.tar" -C "$HOME/.local/share"`
- `tar -xf "$HOME/vrs_main.tar"  -C "$HOME"`
- Start VRS (`vrs -gui`)
- Tools -> Options
  - Change the username in the four "Data Sources" fields.
- Tools -> Plugins
  - Change the username in the settings for these 3 plugins:
    - Custom Content
    - Database Writer
    - Tile Server Cache

There are other ways to go about this.  But, this is just one way.

UPDATE: As I was about to submit this, I just now realized there are also a couple other small issues as well.  In the end, I think it is just easier to create a user on the second server with the same username as the one used on the original server.  You would have a perfectly fine transfer in this case.

**Comment by rikgale** [comment]
Thank you for all the detail. Yes, in future it would be a lot easier to have the same user name... just Pi as a user on a Ubuntu set up feels a bit odd. Ended up with trial and error until I got it all working as it should. If it weren't for that pesky LocalAircraft.txt bug in preview 10 then this would never have come up. Thanks again for all your pointer and help with this. :)
