### ISSUE TITLE
error 79 

### ISSUE THREAD

**Issue by f5gkw** [mypiaware/virtual-radar-server-installation#16]
On raspberry PI3/buster
installation option  preview 3.0.0.0 /10
error 79 , script install stopped.

I had to create the directory '/usr/local/bin/'

touch: impossible de faire un touch '/usr/local/bin/vrs': Aucun fichier ou dossier de ce type
ERROR! Failed to create /usr/local/bin/vrs!
Error Code: 79

**Comment by mypiaware** [comment]
Hello and thank you for your interest in my project!

Sorry you received that error message.  Thank you for providing the Error Code number which really helps to isolate where in the code the error occurred.

However, I am unable to see any issue with my code.  The `/usr/local/bin` directory should always be present by default in a Raspberry Pi OS.  (In fact, it should be present in just about all Linux distributions.)

If you are saying you had to create the `/usr/local/bin` directory, I can only think the issue was with your installation of Raspberry Pi OS.  My script would never delete such a directory.  It would be interesting to see if you tried to use my script again on a clean installation of Raspberry Pi OS.  I am guessing your installation is possibly not a clean installation as you are using an older version of Raspberry Pi OS (Buster).

I can think about this some more.  But, currently, I cannot think of anything to fix my script.  I could probably add a check to make sure the entire `/usr/local/bin` directory path exists prior to creating the `/usr/local/bin/vrs` file.  I just never thought of doing that because the `/usr/local/bin` directory should already be there. This script has been used countless number of times from so many people without having this issue that you are reporting.

**Comment by f5gkw** [comment]
Hi,
Thanks for the reply.
As I wrote it is a buster version.
For sure, your installation script did not delete the folder. 
I did not installed it myself.
I had flashed the SD card with an .IMG prepared by another ham with an AOR DV1 application.
 the /usr/local/bin was not present, only usr/bin was.
Sorry for disturb !
thanks for your job !
Very best regards from France
Jean-Philippe

**Comment by mypiaware** [comment]
Ah OK.  Thanks for that update.  I am glad you were able to get my script to work on your installation.

Take care!
