### ISSUE TITLE
Installation error - Failed to untar VirtualRadar.tar.gz!

### ISSUE THREAD

**Issue by Vialonyx** [mypiaware/virtual-radar-server-installation#17]
Hello,
I'm trying to install VRS via this script on a virtualized debian 12 server installed for the occasion.

I get a fatal error after users input, apparently when the script extracts the VirtualRadar.tar.gz archive.

`gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
ERROR! Failed to untar VirtualRadar.tar.gz!
Error Code: 12
`

Here is the full log : [vrs.log](https://github.com/mypiaware/virtual-radar-server-installation/files/15052636/vrs.log)

Thanks in advance!

**Comment by mypiaware** [comment]
Thanks for your interest in my script!  I am sorry you had the error.  Thank you for including the log as it helps me a lot.  I did a test run on a clean system, and it installed the Stable version just fine on Debian Bookworm.  I see you are trying to use the Stable version, so that is what I tried as well.  At the moment, I can only think of two things:  (1) The VRS tar.gz files did not download.  (2)  The VRS tar.gz files did download, but they were corrupted.

Please try the following three things:


**1.** Run the following two commands & report what is displayed after each command is run.
```
md5sum /tmp/vrs/VirtualRadar.tar.gz
md5sum /tmp/vrs/VirtualRadar.LanguagePack.tar.gz
```

**2.** Delete the temporary directory holding any files downloaded by this script.  The reason for this is because if you run the script again, and the script sees any needed files are already in the `/tmp/vrs` directory, it will use the locally stored files in that directory as opposed to trying to download it again.  If you initially downloaded a corrupt file, you would actually continually try to install the same corrupt file.  You can run this command to completely remove the `/tmp/vrs` directory and all of the files in it.  (FYI - rebooting the system should also delete this directory.)
```
rm -rf /tmp/vrs
```
**3.** Try to install VRS again in the same manner as before and be sure to install the Stable version again.  If you get the same error message, run these same two commands again and report again what is displayed after each command is run.
```
md5sum /tmp/vrs/VirtualRadar.tar.gz
md5sum /tmp/vrs/VirtualRadar.LanguagePack.tar.gz
```

Please let me know if this helps.

**Comment by mypiaware** [comment]
After 4 weeks, I never heard back from the original poster.  However, I do not believe the issue explained here has anything to do with the VRS installation script.  I believe one or more necessary files that were downloaded were corrupt.
