### ISSUE TITLE
Auto Start on boot not working & Setting username and password for WebAdmin

### ISSUE THREAD

**Issue by rikgale** [mypiaware/virtual-radar-server-installation#4]
Script installs and working fine (but slowly) on headless Pi Zero. Despite following instructions on autostarting at boot, this does not appear to work and the webpage  times out, but works fine once I do a manual start vrs -nogui

Also could setting username and password be part of the script for WebAdmin? I did this manually using mono /home/user/VirtualRadarServer/Installation/VirtualRadar.exe -nogui -createadmin:admin -password:password

Thanks
R

p.s. done some further digging. It would appear that it is auto  running, but on port 8080, rather than the default port 8090 which was set during the installation. None of the settings have been set and defaults my postion to back to just outside London. Also the webadmin page runs on port 8080 rather than the default and then doesn't recognise the user name and password I set up. If it could auto run on the port that was set up during installation that would be great! Cheers.

**Comment by mypiaware** [comment]
Thank you very much for your interest in my script!  I am sorry you are having some difficulty.  You mentioned a number of things, I will try to cover them all.

What Operating System are you using?  I assume you are using Raspbian Lite (not with Desktop) because you are running on a Raspberry Pi Zero.  (I make this assumption because Raspbian with Desktop is painfully slow on a RPi Zero, and you are trying to use the Web Admin.)  The script will take some time to install because installing Mono on a RPi Zero will take some time.

I took a RPi Zero with a clean install of Raspbian Lite and then ran the same one-line command I posted in the instructions.  I went ahead and entered "y" for the 4 optional downloads.  Hit "Enter" to use the default port number of 8090.  Entered "15" for my language.  I chose "y" to enter my GPS coordinates, and entered my GPS coordinates.  I chose "y" to enter the receiver information, and entered the receiver information.

The installation on the RPi Zero took about 10 minutes.

At the end of the installation, if you are running on Raspbian Lite, the script should detect you are in a command-line environment, and it should ask you if you want to create a username and password.  Here is exactly what I saw at the end of my installation.  Let me know if you saw the following.  This is a copy/paste from PuTTY of what I saw:

> Virtual Radar Server installation is complete!
> What would you like to do?:
>  1. Create username & password for the VRS Web Admin & start VRS
>  2. Exit
> 
> Enter choice:

After I selected "1" and then created the username and password for the Web Admin, VRS started and worked just fine.  When I went to the VRS map, I used port 8090, and it was centered on the GPS coordinates I entered, and it was displaying planes from the receiver that I entered.  Just understand that running VRS on a RPi is going to be very slow.  I timed how long it took to bring up the VRS map on a local computer and it was just over 1 minute.  Web Admin on a RPi Zero is actually even more painfully slower.

I am glad you determined the autostart was working.  I also tested it, and it also worked for me.  It worked on port 8090 as expected after I rebooted the system.  The Web Admin also worked on port 8090 for me using the username & password that I set from my installation script.

In short, I am unable to replicate any of the issues you are having.  I will need more information please to continue finding any possible issue with the script.

Please try the following:
1. Use a CLEAN installation of Raspbian Lite
2. Run my command line to install VRS
3. Answer all of the questions
4. Let it install
5. When asked to create username & password, please do so. (This will also start VRS.)
6. When VRS completely loads (it will eventually say "Press Q to quit"), press "q" to quit.
7. Now try starting VRS by using the simple "vrs" command, and see if it works for you.

Also, you said you got the autostart to work.  Make sure you are not running multiple instances of VRS.  You could be running one instance of VRS from autorun, and the other from manually entering "vrs".  By the way, you should not need to type "vrs -nogui" as the "vrs" command should detect you are running in a command line environment and automatically use the "-nogui" parameter.  However, adding "-nogui" does not have any negative effect.

Just curious... are you running this script under a general account like the "pi" user?

**Comment by rikgale** [comment]
Hi. I am running Raspbian Lite on the Pi Zero I have set myself up another account and installed under this account rather than the pi account and believe that I have managed to give myself permissions (sudo usermod -a -G adm,dialout,cdrom,sudo,audio,video,plugdev,games,users,input,netdev,gpio,i2c,spi richard) I should probably let you know that I am a bit of a linux newbie at the moment, on a steep learning curve.
I believe I followed what you did when I first installed it. I will reset my image and start again.

As an aside. I have got this running (with auto start) on my Pi4 feeder using port 8080 as I am using the ADSBExchange Image (Feeding ADSBExchange, FR24, FA, PF and Openskies) so I am not using 8080 for anything else, so it fits nicely on my feeder at the moment, but I feel that I should try again on the Pi Zero, which I use for testing as I do not really want to 'break' my feeder.

I will, over the next few days, find some time to try explicitly following your instructions and feedback to you.
Thank you.

**Comment by mypiaware** [comment]
Thank you for getting back with me.  I just now did a test with my RPi Zero and Raspbian Lite.  This time I tried to install it under a newly created account with your same settings.  The following was done on a clean installation of Raspbian Lite first under the "pi" user account:

`sudo useradd -m richard  # The '-m' is important to create the '/home/richard/' directory.`
`sudo passwd richard  # This allowed me to create a password for the newly created account.`
`sudo usermod -a -G adm,dialout,cdrom,sudo,audio,video,plugdev,games,users,input,netdev,gpio,i2c,spi richard`

I then logged out of the 'pi' account and logged back in under the 'richard' account and ran my installation script.  It installed just fine and operated just as expected.  So, I am still unfortunately unable to replicate your issue.

After doing this experiment, I realized you said you are using an ADSBExchange image.  (Therefore probably making the above experiment useless.)  I never used ADSBExchange.  I will probably need to look into it to really try to replicate your issue.  With some other things going on, it may not be for another few days at least before I can look into it.

**Comment by rikgale** [comment]
Hey. Probably should have made it clearer in my 2nd post. I am running the ADSBEx image on a seperate Pi4 which (in my original test) was feeding the VRS on the Pi Zero. The Pi Zero has a Raspian Lite Image with a few settings baked into the image such as WiFi details and user set as richard. Each time I start from the basic image I set static IP and that's about it. I try and test anything I am putting on my feeder on the Pi Zero first. As a newbie I don't really want to have to go back and redo my work or loose data I have collected re-imagine from a back up.

I am hoping to run your script again today and see where I get. I expect I just made a rookis mistake somewhere. Will see.

**Comment by rikgale** [comment]
Ok, followed your instrutions, but it did not give me the option to put in Usr and Pwd. It just asked me if I would like to start VRS at the end. I do so and it pulled up an admin GUI on my desktop. I am remoting in using Mobxterm on a Win10 machine. I am sure it did this the first time I ran the installation... second time (when using a fresh base image with my usr name and wifi set up) it did give me the option.


Virtual Radar Server installation is complete!
What would you like to do?:
 1. Start VRS now
 2. Exit

Enter choice: 1
WARNING: The runtime version supported by this application is unavailable.
Using default runtime: v4.0.30319
Gtk not found (missing LD_LIBRARY_PATH to libgtk-x11-2.0.so.0?), using built-in colorscheme

**Comment by mypiaware** [comment]
Ok, we are probably getting closer to the problem.  The script is not recognizing that you are in a command-line only environment - which is what the Raspbian Lite image is.  If it recognizes you are in a command-line environment, it will assume you will need Web Admin and provide the username/password option.  On your Raspbian Lite system, can you do this one very quick command and tell me what you get?  It is very important you run the command _exactly_ as you see it here.  It is case-sensitive - "DISPLAY" must be in all caps.

`echo $DISPLAY`

The result I am expecting is that you just get nothing but a blank line.  If you get any text at all from the result of running this command, then that is a problem.

Interesting... I am just now noticing that the Raspbian name is now deprecated.  It is now "Raspberry Pi OS", and a new version was released last week.  I wonder if there is some significant changes because I have been using the next-latest Raspbian Lite image which was released back in February.  I should try to test my script with the latest version.  Which version are you using?

**Comment by mypiaware** [comment]
I figured it out.  I tried it using MobaXterm.  When I run the `echo $DISPLAY` command, it produces some text - which I never expected it to do.  So, when you run my script through MobaXterm, my script will think you are in a GUI desktop environment and not bother to ask you if you want to set up the username & password for the Web Admin.  Easy solution for me is to simply always provide that option, I guess.  But, my thinking was to force a novice user to create the username & password for the Web Admin, otherwise they will never be able to access the settings.  I will think about it some more.

But, for now, just run the script as normal.  When you get to the end, do not choose the option to start VRS.  Just simply exit, and then you will need to do the `mono /home/richard/VirtualRadarServer/Installation/VirtualRadar.exe -nogui -createadmin:admin -password:password` command yourself.  All of the other parts of the script should not be affected.  Therefore, you still get all the usefulness of the script.

Only other change you will need to do is to make sure you start VRS with the `vrs -nogui` command if you do not want the GUI interface appearing.  In an earlier post, I told you that adding the '-nogui' parameter was unnecessary when in a command-line environment.  However, if you are going to use MobaXterm, then you will need to specifically tell it you are in a command-line environment by adding the '-nogui' parameter.

Let me know if this helps.

**Comment by rikgale** [comment]
Hey, thanks for your further comments. I will test again on a fresh image when I next get a chance (probably over the weekend) and test for port 8090 with autostart.

When I did get it working on the second install I did what you had suggested, exit at the end of the script run and set admin and pwd manually but had set it to use port 8080 at that point and set up the admin using mono /home/richard/VirtualRadarServer/Installation/VirtualRadar.exe -nogui -createadmin:admin -password:password 

Did the same on my live feeder Pi4, so it did all install fine just that it is running on port 8080 rather than port8090 as per the script default.

Rather than altering your script just put something in the readme about using Mobxterm and what to do at the end. I appreciate that you are relying on poeple to RTFM, which is what I try to do before contacting a dev.

I will let you know when I have had another chance to test.

**Comment by mypiaware** [comment]
I made some changes to the script, and the updated script has now been posted.

Some changes:

- Removed the autorun script.
- End of the installation will not ask if you want to start VRS.
- The 'vrs' command has been greatly changed.

The last part was the biggest update of my script.  I have now made the 'vrs' command a pretty powerful tool.  I have updated the README.  So, you can find all the details here: https://github.com/mypiaware/virtual-radar-server-installation#global-command-to-start-vrs

**Comment by rikgale** [comment]
Hey. Sorry for the slow response. Have tested the new version and all appears to work as described in the readme. Many thanks. Also had a guy from a forum I use run your script the other day and he said it all installed fine :)
One question. Will I be able to install this on a system that already has VRS installed via the old verion of your script. If I change the port during the installation from the one already set up during the previous install do you know what will happen?
Many thanks

**Comment by mypiaware** [comment]
Many thanks for testing it out.  You should definitely be able to run the script again on your existing VRS installation without any issues.  I would do the following:

- All of the yes/no questions should just be answered with a 'no'.
- The port number question should have your current existing port as the default port number.  So, just press [Enter] to accept your existing port number.
- The language question should still be answered accordingly.

The script will not go through the long process of installing Mono as it should recognize that it is already installed.  Because of this, the script will be much faster than the first time you ran it.

The script will still download & extract the VRS program files, but that will not affect anything as you will just be overwriting your existing VRS program files with the same ones.  (Of course, I am assuming by the time you run the script, VRS has not released an updated version of VRS.)

In the end, running the new script will essentially just be upgrading the 'vrs' command to the new version with all of its options.  Hope it works out for you.

**Comment by rikgale** [comment]
Hey. Took the plunge anyway before you reponded as I liked the new features of the 'vrs' command. Ended up doing what you have suggested, but stupidly answered Y rather than N to all the questions, so ended up overwritting a few things but nothing important. Kept the database which was the most important part for me. Many thanks for your assistance in getting it all sorted. If you need anyone to test any future updates please let me know.
