### ISSUE TITLE
Upgrade to latest Preview Version.

### ISSUE THREAD

**Issue by ataa** [mypiaware/virtual-radar-server-installation#5]
Thank you for this easy to use script, 
Is there an easy way to upgrade the VRS and it's plugins to latest preview version (v3.0.0-preview-1)?

**Comment by mypiaware** [comment]
Thank you very much for your interest in this script!  It just so happens that I was going to release a slightly updated version of my script probably as soon as this weekend that may offer a choice to install either the current stable release (ver 2.4.4) or the preview edition (ver 3.0.0).  My main reason for giving the option to download the preview edition is because of the Mono issue that I discuss in the Readme.  The preview edition seems to run better on newer versions of Mono, and the newer versions of Mono are the versions getting installed on the latest releases of Ubuntu and Fedora.

For the time being, if you want to use my script to install the preview edition instead, simply do the following:
- Download the script to your drive.
- Edit the script by deleting the `VRSFILES` array starting at line 97.
- Replace the `VRSFILES` array that you just deleted with the `VRSFILES` array posted below.
- Run the script with: `bash virtual_radar_server_install.sh`

```
VRSFILES=(
   "https://github.com/vradarserver/vrs/releases/download/v3.0.0-preview-1-mono/VirtualRadar-3.0.0-preview-1.tar.gz"
   "https://github.com/vradarserver/vrs/releases/download/v3.0.0-preview-1-mono/LanguagePack-3.0.0-preview-1.tar.gz"
   "https://github.com/vradarserver/vrs/releases/download/v3.0.0-preview-1-mono/Plugin-CustomContent-3.0.0-preview-1.tar.gz"
   "https://github.com/vradarserver/vrs/releases/download/v3.0.0-preview-1-mono/Plugin-DatabaseEditor-3.0.0-preview-1.tar.gz"
   "https://github.com/vradarserver/vrs/releases/download/v3.0.0-preview-1-mono/Plugin-DatabaseWriter-3.0.0-preview-1.tar.gz"
   "https://github.com/vradarserver/vrs/releases/download/v3.0.0-preview-1-mono/Plugin-FeedFilter-3.0.0-preview-1.tar.gz"
   "https://github.com/vradarserver/vrs/releases/download/v3.0.0-preview-1-mono/Plugin-TileServerCache-3.0.0-preview-1.tar.gz"
   "https://github.com/vradarserver/vrs/releases/download/v3.0.0-preview-1-mono/Plugin-WebAdmin-3.0.0-preview-1.tar.gz"
)
```

**Comment by ataa** [comment]
Thank you for your detailed reply. I made the changes but I got timeout on connecting to github https, not sure why! I can download the same files using browser but not using wget!
So I will wait for your update.

**Comment by mypiaware** [comment]
Interesting.  Doing the same steps I gave above worked for me.  I will try to get the script updated soon.  I am hoping for this weekend.  I just do not like to release anything without significant testing.  But, there is a lot of personal things going on right now.  Sorry.

**Comment by mypiaware** [comment]
Hi, I released the new version of my script.  You will see that you have the option of which version of VRS to install.  And, you can always change from one version to another.  Just run the script again, and you can simply select the other version to install.  Let me know what you think.
